### ISSUE TITLE
SimVIT models

### ISSUE THREAD

**Issue by Azong-HQU** [ucasligang/SimViT#1]
Hi ! Will you upload other versions of SimVIT models (SimViT-Tiny, SimViT-Small, SimViT-Medium and SimViT-Large) ? I can only find the SimViT-Micro version now.

**Comment by ucasligang** [comment]
Thank you for your attention to our work. At present, we have published our three pre-trained models: SimViT-micro, SimViT-tiny and SimViT-small,  we will sort out and publish our remaining pre-trained models(including models of object detection and semantic segmentation) soon.

Sincerely,
Gang Li.
